### ISSUE TITLE
For traces

### ISSUE THREAD

**Issue by i4mhmh** [AISyLab/AES_HD#2]
Dear author，

For AES_HD,AES_RD, I want to test my model in each key bytes, but I found the traces is just for the single byte.So could you please to share the raw traces for all bytes?

**Comment by AISyLab** [comment]
Hi. AES_RD is not our dataset (measured by us) so we do not have anything else.
For AES_HD, we also gave (in version 2) all that we have.


Best,
Stjepan

Poslano iz aplikacije Outlook za Android<https://aka.ms/AAb9ysg>
________________________________
From: 全世界的面我都吃一遍 ***@***.***>
Sent: Sunday, January 14, 2024 5:14:06 AM
To: AISyLab/AES_HD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AISyLab/AES_HD] For traces (Issue #2)


Dear author，

For AES_HD,AES_RD, I want to test my model in each key bytes, but I found the traces is just for the single byte.So could you please to share the raw traces for all bytes?

**Comment by i4mhmh** [comment]
All right, thanks a lot!
